name: 'Github Tag Bump'
description: 'Bump and push git tag'

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@master
    - name: run script
      continue-on-error: false
      run:  ${{ github.action_path }}/entrypoint.sh
      shell: bash